server:
  port: 9093
  ssl:
    key-store: classpath:static/security/keystore.p12
    key-store-password: mypassword
    key-password: mypassword
    key-alias: mykey
    enabled: true
  servlet:
    context-path: /api


spring:
  application:
    name: master-service-dev

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

logging:
  config: classpath:logging/logback-master.xml

application:
  sms-verification:
    prefix: "verify:"
    ttl-minutes: 5
    code-length: 6

  security:
    jwt:
      access-token:
        expiration: 120 #minute
      refresh-token:
        expiration: 14400 #minute -> 10 day
      keys:
        public: ${JWT_PUBLIC_KEY_PATH}
        private: ${JWT_PRIVATE_KEY_PATH}

    cors-allowed-origins:
      - "http://localhost:3000"
      - "https://localhost:3000"
      - "http://localhost:9090"
      - "https://localhost:9090"
    public-endpoints:
      - method: POST
        path: /auth/register-or-login
      - method: GET
        path: /auth/refresh
      - method: GET
        path: /auth/logout
      - method: POST
        path: /auth/verify
      - method: POST
        path: /auth/resend-code
      - method: GET
        path: /auth/get-all-code
      - method: GET
        path: /enums/**
      - method: GET
        path: /cities
      - method: GET
        path: /service-categories
      - method: GET
        path: /subservice-categories
      - method: GET
        path: /news
      - method: GET
        path: /news/*/image
      - method: GET
        path: /v2/api-docs
      - method: GET
        path: /v3/api-docs/**
      - method: GET
        path: /swagger-resources/**
      - method: GET
        path: /configuration/**
      - method: GET
        path: /swagger-ui/**
      - method: GET
        path: /webjars/**

  doc-file:
    allowed-types:
      - image/png
      - image/jpeg
      - image/jpg
    file-path: "./src/main/resources/static"
    images-sub-dir: "photos"