debug: true

server:
  port: 9093
  ssl:
    key-store: classpath:static/security/keystore.p12
    key-store-password: mypassword
    key-password: mypassword
    key-alias: mykey
    enabled: true
  servlet:
    context-path: /api


spring:
  application:
    name: master-service-dev

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/dev/changelog_dev.yml

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

logging:
  config: classpath:logging/logback-dev.xml

application:
  verification:
    prefix: "verify:"
    ttl-minutes: 5
    code-length: 6

  security:
    jwt:
      access-token:
        expiration: 1200 #minute
      refresh-token:
        expiration: 14400 #minute -> 10 day
      keys:
        public: ${JWT_PUBLIC_KEY_PATH}
        private: ${JWT_PRIVATE_KEY_PATH}

    cors-allowed-origins:
      - "http://localhost:3000"
      - "https://localhost:3000"
      - "http://localhost:9090"
      - "https://localhost:9090"
    public-endpoints:
      - method: POST
        path: /payments/create
      - method: POST
        path: /payments/webhook
      - method: GET
        path: /payments/status/*
      - method: POST
        path: /auth/register-or-login
      - method: POST
        path: /admin/register
      - method: POST
        path: /admin/login
      - method: PATCH
        path: /admin/password/reset-request
      - method: PATCH
        path: /admin/password/reset-confirm
      - method: POST
        path: /auth/refresh
      - method: GET
        path: /auth/logout
      - method: POST
        path: /auth/verify
      - method: POST
        path: /auth/resend-code
      - method: GET
        path: /auth/get-all-code
      - method: GET
        path: /enums/**
      - method: GET
        path: /cities
      - method: GET
        path: /service-categories
      - method: GET
        path: /subservice-categories
      - method: GET
        path: /news
      - method: GET
        path: /news/*/image
      - method: GET
        path: /users/*/verification-status
      - method: GET
        path: /service-categories/*/image
      - method: GET
        path: /service-categories/with-sub-service
      - method: GET
        path: /client-orders/*
      - method: GET
        path: /v2/api-docs
      - method: GET
        path: /v3/api-docs/**
      - method: GET
        path: /swagger-resources/**
      - method: GET
        path: /configuration/**
      - method: GET
        path: /swagger-ui/**
      - method: GET
        path: /webjars/**

  doc-file:
    allowed-types:
      - image/png
      - image/jpeg
      - image/jpg
    file-path: "./src/main/resources/static"
    images-sub-dir: "photos"

  email:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

  yookassa:
    shop-id: ${YOOKASSA_SHOP_ID}
    secret-key: ${YOOKASSA_SECRET_KEY}
    return-url: ${YOOKASSA_RETURN_URL}
    test-mode: true # false для продакшена

  yandex:
    s3:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
      region: ${REGION}
      endpoint: https://storage.yandexcloud.net
      bucket: ${BUCKET}
      allowed-types:
        - image/png
        - image/jpeg
        - image/jpg